### ISSUE TITLE
Please Note The New Rules

### ISSUE THREAD

**Issue by HarshKhandeparkar** [atl-ponda/smart-car-parking#29]
1. No one can directly commit to master branch.
2. Each commit should be a pr.
3. New branch for each pr.
4. One approved review before merging pr.

**Comment by HarshKhandeparkar** [comment]
@sahil-patel6 @Harshithpabbati

**Comment by sahil-patel6** [comment]
Noted!!!

**Comment by HarshKhandeparkar** [comment]
:+1:

**Comment by Harshithpabbati** [comment]
:+1:

**Comment by HarshKhandeparkar** [comment]
:+1: Thanks.

**Comment by Harshithpabbati** [comment]
Hey i don't have access to label.

**Comment by Harshithpabbati** [comment]
Close issues and further.!

**Comment by HarshKhandeparkar** [comment]
Ok. I'll give you access.
